version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # These are released daily, so limit to minor updates
      # https://mvnrepository.com/artifact/software.amazon.awssdk/bom
      - dependency-name: software.amazon.awssdk:bom
        update-types: [ version-update:semver-patch ]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
